version: "3.7"

volumes:
  serene-database:

services:
  serene-db:
    env_file: serene-db.env
    image: mongo:4.0.6
    volumes:
      - type: volume
        source: serene-database
        target: /data/db
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 127.0.0.1:37017:27017
      - 127.0.0.1:38017:28017
    restart: unless-stopped

  serene-backend:
    build: ./backend
    env_file: lad-backend.env
    depends_on:
      - serene-db
    expose:
      - 8080
    ports:
      - 127.0.0.1:3001:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/lad-backend/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s

  serene-frontend:
    build:
      context: ./frontend
      args:
        RUNNING_ENVIRONMENT: dev
    depends_on:
      - serene-backend
    expose:
      - 8080
    ports:
      - 127.0.0.1:3000:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s
